import StatusTag from "../components/atoms/StatusTag";
import TableAction from "../components/molecules/TableAction";

export const deleteReasonHeaders = [
  "No:",
  "Reason",
  "Date of Creation",
  "Last Updated:",
  "Action:",
];
export const deleteReasonData = [
  [
    "1",
    <StatusTag content="Soiled beyond repair" variant="danger"></StatusTag>,
    "2024-11-18",
    "2032-11-18",
    <TableAction itemId={1} showEdit showTrash />,
  ],
  [
    "2",
    <StatusTag content="Lost during transit" variant="danger"></StatusTag>,
    "2024-11-19",
    "2024-11-20",
    <TableAction itemId={2} showEdit showTrash />,
  ],
  [
    "3",
    <StatusTag content="Size mismatch" variant="danger"></StatusTag>,
    "2024-11-20",
    "2024-11-22",
    <TableAction itemId={3} showEdit showTrash />,
  ],
  [
    "4",
    <StatusTag content="Fabric defect" variant="danger"></StatusTag>,
    "2024-11-21",
    "2024-11-23",
    <TableAction itemId={4} showEdit showTrash />,
  ],
  [
    "5",
    <StatusTag content="Customer returned" variant="danger"></StatusTag>,
    "1994-11-22",
    "2078-11-25",
    <TableAction itemId={5} showEdit showTrash />,
  ],
  [
    "6",
    <StatusTag content="Color faded" variant="danger"></StatusTag>,
    "2024-11-23",
    "2024-11-26",
    <TableAction itemId={6} showEdit showTrash />,
  ],
  [
    "7",
    <StatusTag content="Wrong item delivered" variant="danger"></StatusTag>,
    "2024-11-24",
    "2024-11-27",
    <TableAction itemId={7} showEdit showTrash />,
  ],
  [
    "8",
    <StatusTag content="Torn during usage" variant="danger"></StatusTag>,
    "2024-11-25",
    "2024-11-28",
    <TableAction itemId={8} showEdit showTrash />,
  ],
  [
    "9",
    <StatusTag content="Overstock clearance" variant="danger"></StatusTag>,
    "2024-11-26",
    "2024-11-29",
    <TableAction itemId={9} showEdit showTrash />,
  ],
  [
    "10",
    <StatusTag content="Outdated style" variant="danger"></StatusTag>,
    "2024-11-27",
    "2024-11-30",
    <TableAction itemId={10} showEdit showTrash />,
  ],
  [
    "11",
    <StatusTag content="Shrinkage after washing" variant="danger"></StatusTag>,
    "2024-11-28",
    "2024-12-01",
    <TableAction itemId={11} showEdit showTrash />,
  ],
  [
    "12",
    <StatusTag content="Unclaimed order" variant="danger"></StatusTag>,
    "2024-11-29",
    "2024-12-02",
    <TableAction itemId={12} showEdit showTrash />,
  ],
  [
    "13",
    <StatusTag content="Misaligned stitching" variant="danger"></StatusTag>,
    "2024-11-30",
    "2024-12-03",
    <TableAction itemId={13} showEdit showTrash />,
  ],
  [
    "14",
    <StatusTag content="Customer dissatisfaction" variant="danger"></StatusTag>,
    "2024-12-01",
    "2024-12-04",
    <TableAction itemId={14} showEdit showTrash />,
  ],
  [
    "15",
    <StatusTag content="End of promotion stock" variant="danger"></StatusTag>,
    "2024-12-02",
    "2024-12-05",
    <TableAction itemId={15} showEdit showTrash />,
  ],
  [
    "16",
    <StatusTag content="Incorrect labeling" variant="danger"></StatusTag>,
    "2024-12-03",
    "2024-12-06",
    <TableAction itemId={16} showEdit showTrash />,
  ],
  [
    "17",
    <StatusTag content="Unauthorized duplication" variant="danger"></StatusTag>,
    "2024-12-04",
    "2024-12-07",
    <TableAction itemId={17} showEdit showTrash />,
  ],
  [
    "18",
    <StatusTag content="Trial design prototype" variant="danger"></StatusTag>,
    "2024-12-05",
    "2024-12-08",
    <TableAction itemId={18} showEdit showTrash />,
  ],
  [
    "19",
    <StatusTag content="Warranty replacement" variant="danger"></StatusTag>,
    "2024-12-06",
    "2024-12-09",
    <TableAction itemId={19} showEdit showTrash />,
  ],
  [
    "20",
    <StatusTag
      content="Custom order cancellation"
      variant="danger"
    ></StatusTag>,
    "2024-12-07",
    "2024-12-10",
    <TableAction itemId={20} showEdit showTrash />,
  ],
];
