import StatusTag from "../components/atoms/StatusTag";

export const shirtInventoryHeaders = [
  "Shirt ID:",
  "Belongs To:",
  "Gender:",
  "Uniform Type:",
  "Shirt Location:",
  "Last drawn date:",
  "Status:",
];
export const shirtInventoryData = [
  [
    "9983747389",
    "Airforce",
    "Male",
    "No. 1",
    "Row: 2, Rack: B1",
    "2024-10-10",
    <StatusTag content="Remarked" variant="warning"></StatusTag>,
  ],
  [
    "9388394738",
    "Navy",
    "Female",
    "Color Party",
    "Row: 2, Rack: B5",
    "2027-11-12",
    <StatusTag content="Loaned" variant="danger"></StatusTag>,
  ],
  [
    "23478911113",
    "Army",
    "Male",
    "Combat",
    "Row: 3, Rack: C2",
    "2025-06-21",
    <StatusTag content="Available" variant="success"></StatusTag>,
  ],
  [
    "1298473290",
    "Airforce",
    "Female",
    "No. 2",
    "Row: 1, Rack: A3",
    "2023-05-17",
    <StatusTag content="Remarked" variant="warning"></StatusTag>,
  ],
  [
    "3482748290",
    "Navy",
    "Male",
    "Ceremonial",
    "Row: 4, Rack: D1",
    "2024-12-01",
    <StatusTag content="Available" variant="success"></StatusTag>,
  ],
  [
    "9848321982",
    "Army",
    "Female",
    "Service Dress",
    "Row: 5, Rack: E4",
    "2026-03-11",
    <StatusTag content="Remarked" variant="warning"></StatusTag>,
  ],
  [
    "9283748394",
    "Airforce",
    "Male",
    "Flight Suit",
    "Row: 3, Rack: C3",
    "2025-08-25",
    <StatusTag content="Available" variant="success"></StatusTag>,
  ],
  [
    "5672838493",
    "Navy",
    "Female",
    "No. 1",
    "Row: 2, Rack: B6",
    "2028-01-01",
    <StatusTag content="Loaned" variant="danger"></StatusTag>,
  ],
  [
    "0983742837",
    "Army",
    "Male",
    "Combat",
    "Row: 6, Rack: F1",
    "2024-11-15",
    <StatusTag content="Available" variant="success"></StatusTag>,
  ],
  [
    "1118749382",
    "Airforce",
    "Female",
    "Service Dress",
    "Row: 4, Rack: D3",
    "2027-07-14",
    <StatusTag content="Loaned" variant="danger"></StatusTag>,
  ],
  [
    "3456382948",
    "Navy",
    "Male",
    "No. 2",
    "Row: 5, Rack: E2",
    "2026-09-05",
    <StatusTag content="Available" variant="success"></StatusTag>,
  ],
  [
    "7823456782",
    "Army",
    "Female",
    "Ceremonial",
    "Row: 7, Rack: G4",
    "2024-02-27",
    <StatusTag content="Remarked" variant="warning"></StatusTag>,
  ],
  [
    "9384757382",
    "Airforce",
    "Male",
    "No. 1",
    "Row: 1, Rack: A5",
    "2025-04-16",
    <StatusTag content="Available" variant="success"></StatusTag>,
  ],
  [
    "1293847382",
    "Navy",
    "Female",
    "Color Party",
    "Row: 2, Rack: B3",
    "2027-08-22",
    <StatusTag content="Remarked" variant="warning"></StatusTag>,
  ],
  [
    "3482748273",
    "Army",
    "Male",
    "Combat",
    "Row: 6, Rack: F2",
    "2024-03-19",
    <StatusTag content="Remarked" variant="warning"></StatusTag>,
  ],
  [
    "9847392837",
    "Airforce",
    "Female",
    "Service Dress",
    "Row: 3, Rack: C1",
    "2026-12-10",
    <StatusTag content="Loaned" variant="danger"></StatusTag>,
  ],
  [
    "9238473829",
    "Navy",
    "Male",
    "No. 1",
    "Row: 4, Rack: D4",
    "2028-05-30",
    <StatusTag content="Available" variant="success"></StatusTag>,
  ],
  [
    "5562383842",
    "Army",
    "Female",
    "Combat",
    "Row: 7, Rack: G2",
    "2024-09-12",
    <StatusTag content="Loaned" variant="danger"></StatusTag>,
  ],
  [
    "0982738474",
    "Airforce",
    "Male",
    "No. 2",
    "Row: 2, Rack: B2",
    "2025-01-10",
    <StatusTag content="Remarked" variant="warning"></StatusTag>,
  ],
  [
    "1211234392",
    "Navy",
    "Female",
    "Ceremonial",
    "Row: 5, Rack: E1",
    "2027-03-25",
    <StatusTag content="Loaned" variant="danger"></StatusTag>,
  ],
];

export const pantsInventoryHeaders = [
    "Pants ID:",
    "Belongs To:",
    "Gender:",
    "Uniform Type:",
    "Pants Location:",
    "Last drawn date:",
    "Status:",
];

export const pantsInventoryData = [
    [
        "P9983747389",
        "Airforce",
        "Male",
        "No. 1",
        "Row: 1, Rack: A1",
        "2024-10-10",
        <StatusTag content="Loaned" variant="danger"></StatusTag>,
    ],
    [
        "P9388394738",
        "Navy",
        "Female",
        "Color Party",
        "Row: 2, Rack: B3",
        "2027-11-12",
        <StatusTag content="Loaned" variant="danger"></StatusTag>,
    ],
    [
        "P23478911113",
        "Army",
        "Male",
        "Combat",
        "Row: 3, Rack: C2",
        "2025-06-21",
        <StatusTag content="Available" variant="success"></StatusTag>,
    ],
    [
        "P1298473290",
        "Airforce",
        "Female",
        "No. 2",
        "Row: 1, Rack: A3",
        "2023-05-17",
        <StatusTag content="Remarked" variant="warning"></StatusTag>,
      ],
    [
        "P3482748290",
        "Navy",
        "Male",
        "Ceremonial",
        "Row: 4, Rack: D1",
        "2024-12-01",
        <StatusTag content="Available" variant="success"></StatusTag>,
    ],
    [
        "P9848321982",
        "Army",
        "Female",
        "Service Dress",
        "Row: 5, Rack: E4",
        "2026-03-11",
        <StatusTag content="Loaned" variant="danger"></StatusTag>,
    ],
    [
        "P9283748394",
        "Airforce",
        "Male",
        "Flight Suit",
        "Row: 3, Rack: C3",
        "2025-08-25",
        <StatusTag content="Available" variant="success"></StatusTag>,
    ],
    [
        "P5672838493",
        "Navy",
        "Female",
        "No. 1",
        "Row: 2, Rack: B6",
        "2028-01-01",
        <StatusTag content="Loaned" variant="danger"></StatusTag>,
    ],
    [
        "P0983742837",
        "Army",
        "Male",
        "Combat",
        "Row: 6, Rack: F1",
        "2024-11-15",
        <StatusTag content="Available" variant="success"></StatusTag>,
    ],
    [
        "P1118749382",
        "Airforce",
        "Female",
        "Service Dress",
        "Row: 4, Rack: D3",
        "2027-07-14",
        <StatusTag content="Loaned" variant="danger"></StatusTag>,
    ],
    [
        "P3456382948",
        "Navy",
        "Male",
        "No. 2",
        "Row: 5, Rack: E2",
        "2026-09-05",
        <StatusTag content="Available" variant="success"></StatusTag>,
    ],
    [
        "P7823456782",
        "Army",
        "Female",
        "Ceremonial",
        "Row: 7, Rack: G4",
        "2024-02-27",
        <StatusTag content="Loaned" variant="danger"></StatusTag>,
    ],
    [
        "P9384757382",
        "Airforce",
        "Male",
        "No. 1",
        "Row: 1, Rack: A5",
        "2025-04-16",
        <StatusTag content="Remarked" variant="warning"></StatusTag>,
      ],
    [
        "P1293847382",
        "Navy",
        "Female",
        "Color Party",
        "Row: 2, Rack: B3",
        "2027-08-22",
        <StatusTag content="Loaned" variant="danger"></StatusTag>,
    ],
    [
        "P3482748273",
        "Army",
        "Male",
        "Combat",
        "Row: 6, Rack: F2",
        "2024-03-19",
        <StatusTag content="Available" variant="success"></StatusTag>,
    ],
    [
        "P9847392837",
        "Airforce",
        "Female",
        "Service Dress",
        "Row: 3, Rack: C1",
        "2026-12-10",
        <StatusTag content="Loaned" variant="danger"></StatusTag>,
    ],
    [
        "P9238473829",
        "Navy",
        "Male",
        "No. 1",
        "Row: 4, Rack: D4",
        "2028-05-30",
        <StatusTag content="Available" variant="success"></StatusTag>,
    ],
    [
        "P5562383842",
        "Army",
        "Female",
        "Combat",
        "Row: 7, Rack: G2",
        "2024-09-12",
        <StatusTag content="Loaned" variant="danger"></StatusTag>,
    ],
    [
        "P0982738474",
        "Airforce",
        "Male",
        "No. 2",
        "Row: 2, Rack: B2",
        "2025-01-10",
        <StatusTag content="Available" variant="success"></StatusTag>,
    ],
    [
        "P1112348392",
        "Navy",
        "Female",
        "Ceremonial",
        "Row: 5, Rack: E1",
        "2027-03-25",
        <StatusTag content="Loaned" variant="danger"></StatusTag>,
    ],
];

